# Generated by Django 3.2.5 on 2021-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_auto_20210728_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='amenities',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='gender',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AddField(
            model_name='hostels',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostels',
            name='rooms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostels',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
